import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col px-4">
        <div className="flex flex-col">
          <Link href={"/"}>back to home</Link>
          <Link href={"/say-hello"}>Go to say hello page</Link>
          <Link href={"/blog"}>Go to blog page</Link>
          <Link href={"/users"}>Go to users page</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
